//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NILAI_REVIEW_PENGABDIAN
    {
        public int ID_NILAI_REVIEW { get; set; }
        public int ID_PROPOSAL { get; set; }
        public string ID_REVIEWER { get; set; }
        public int COUNT_REVISI { get; set; }
        public Nullable<int> SKOR1 { get; set; }
        public Nullable<int> SKOR2 { get; set; }
        public Nullable<int> SKOR3 { get; set; }
        public Nullable<int> SKOR4 { get; set; }
        public Nullable<int> SKOR5 { get; set; }
        public Nullable<int> SKOR6 { get; set; }
        public string JUSTIFIKASI1 { get; set; }
        public string JUSTIFIKASI2 { get; set; }
        public string JUSTIFIKASI3 { get; set; }
        public string JUSTIFIKASI4 { get; set; }
        public string JUSTIFIKASI5 { get; set; }
        public string JUSTIFIKASI6 { get; set; }
        public string CATATAN1 { get; set; }
        public string CATATAN2 { get; set; }
        public string CATATAN3 { get; set; }
        public string CATATAN4 { get; set; }
        public string CATATAN5 { get; set; }
        public string KESIMPULAN { get; set; }
        public Nullable<int> ANGGARAN { get; set; }
        public string ANGGARAN_HURUF { get; set; }
        public string KEUNIKAN { get; set; }
    }
}
