//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NILAI_REVIEW_PENELITIAN
    {
        public int ID_NILAI_REVIEW { get; set; }
        public string ID_PROPOSAL { get; set; }
        public string ID_REVIEWER { get; set; }
        public int COUNT_REVISI { get; set; }
        public Nullable<double> N1_FIELD1 { get; set; }
        public Nullable<double> N1_FIELD2 { get; set; }
        public Nullable<double> N1_FIELD3 { get; set; }
        public Nullable<double> N1_FIELD4 { get; set; }
        public Nullable<double> N1_FIELD5 { get; set; }
        public Nullable<double> N1_FIELD6 { get; set; }
        public Nullable<double> N1_FIELD7 { get; set; }
        public string N1_JUSTIFIKASI1 { get; set; }
        public string N1_JUSTIFIKASI2 { get; set; }
        public string N1_JUSTIFIKASI3 { get; set; }
        public string N1_JUSTIFIKASI4 { get; set; }
        public string N1_JUSTIFIKASI5 { get; set; }
        public string N1_JUSTIFIKASI6 { get; set; }
        public string N1_JUSTIFIKASI7 { get; set; }
        public Nullable<int> DANA_REKOMENDASI { get; set; }
        public Nullable<int> DANA_SETUJU { get; set; }
    }
}
