//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_RAB_PENGABDIAN
    {
        public int ID_DTL_RAB_PENGABDIAN { get; set; }
        public Nullable<int> ID_RAB_PENGABDIAN { get; set; }
        public Nullable<decimal> JUMLAH_DANA { get; set; }
        public Nullable<int> JUMLAH { get; set; }
        public string SATUAN { get; set; }
        public Nullable<decimal> HARGA_SATUAN { get; set; }
        public string KETERANGAN { get; set; }
    }
}
