//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_LEVEL_SEMINAR
    {
        public REF_LEVEL_SEMINAR()
        {
            this.TBL_PUBLIKASI_SEMINAR = new HashSet<TBL_PUBLIKASI_SEMINAR>();
        }
    
        public int ID_LEVEL_SEMINAR { get; set; }
        public string LEVEL { get; set; }
    
        public virtual ICollection<TBL_PUBLIKASI_SEMINAR> TBL_PUBLIKASI_SEMINAR { get; set; }
    }
}
