//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_JENIS_PENELITIAN
    {
        public REF_JENIS_PENELITIAN()
        {
            this.TBL_PENELITIAN = new HashSet<TBL_PENELITIAN>();
        }
    
        public int ID_JENIS_PENELITIAN { get; set; }
        public string JENIS_PENELITIAN { get; set; }
    
        public virtual ICollection<TBL_PENELITIAN> TBL_PENELITIAN { get; set; }
    }
}
