//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_LEVEL_JURNAL
    {
        public REF_LEVEL_JURNAL()
        {
            this.TBL_PUBLIKASI_JURNAL = new HashSet<TBL_PUBLIKASI_JURNAL>();
        }
    
        public int ID_LEVEL_JURNAL { get; set; }
        public string LEVEL { get; set; }
    
        public virtual ICollection<TBL_PUBLIKASI_JURNAL> TBL_PUBLIKASI_JURNAL { get; set; }
    }
}
