//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_KATEGORI
    {
        public int ID_KATEGORI { get; set; }
        public string KATEGORI { get; set; }
        public string DETAIL_PELAKU { get; set; }
        public string DETAIL_BEBAN_SKS { get; set; }
        public string DESKRIPSI { get; set; }
        public Nullable<bool> IS_CURRENT { get; set; }
    }
}
