//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONIL_PENELITIAN
    {
        public int ID_PERSONIL_PENELITIAN { get; set; }
        public string NPP { get; set; }
        public string NAMA_LENGKAP_GELAR { get; set; }
        public string TEMPAT_LAHIR { get; set; }
        public Nullable<System.DateTime> TGL_LAHIR { get; set; }
        public string JNS_KEL { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ID_REF_FUNGSIONAL { get; set; }
        public Nullable<int> ID_UNIT { get; set; }
        public Nullable<int> ID_UNIT_AKADEMIK { get; set; }
        public string ID_REF_GOLONGAN { get; set; }
        public Nullable<int> ID_REF_JBTN_AKADEMIK { get; set; }
        public string NO_TELPON_RUMAH { get; set; }
        public string NO_TELPON_HP { get; set; }
        public string WARGANEGARA { get; set; }
        public string NPWP { get; set; }
        public string NIP_PNS { get; set; }
        public string NIDN { get; set; }
        public string ALAMAT_KOTA { get; set; }
        public string ALAMAT { get; set; }
        public string ALAMAT_PROVINSI { get; set; }
        public string ALAMAT_KODEPOS { get; set; }
        public int ID_PROPOSAL { get; set; }
        public string INSTITUSI_ASAL { get; set; }
        public string BIDANG_KEAHLIAN_PENELITIAN { get; set; }
    }
}
