//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RAB_PENELITIAN
    {
        public TBL_RAB_PENELITIAN()
        {
            this.DTL_RAB_PENELITIAN = new HashSet<DTL_RAB_PENELITIAN>();
        }
    
        public int ID_RAB_PENELITIAN { get; set; }
        public int ID_PROPOSAL { get; set; }
        public int ID_PENGELUARAN_RAB { get; set; }
        public decimal JUMLAH_DANA { get; set; }
        public Nullable<decimal> PERSENTASE { get; set; }
    
        public virtual ICollection<DTL_RAB_PENELITIAN> DTL_RAB_PENELITIAN { get; set; }
        public virtual REF_PENGELUARAN_RAB REF_PENGELUARAN_RAB { get; set; }
    }
}
