//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PENELITIAN_LOLOS
    {
        public int ID_PROPOSAL { get; set; }
        public string NPP { get; set; }
        public string JENIS { get; set; }
        public int ID_TAHUN_ANGGARAN { get; set; }
        public bool IS_CHECKED { get; set; }
        public string REVIEWER1 { get; set; }
        public string REVIEWER2 { get; set; }
        public string JUDUL { get; set; }
        public int ID_KATEGORI { get; set; }
        public string LOKASI { get; set; }
        public Nullable<int> BEBAN_SKS { get; set; }
        public Nullable<int> ID_STATUS_PENELITIAN { get; set; }
        public Nullable<decimal> DANA_USUL { get; set; }
        public Nullable<System.DateTime> AWAL { get; set; }
        public Nullable<System.DateTime> AKHIR { get; set; }
        public byte[] DOKUMEN { get; set; }
        public Nullable<bool> IS_DROPPED { get; set; }
        public string KEYWORD { get; set; }
        public Nullable<double> JARAK_KAMPUS_KM { get; set; }
        public Nullable<int> JARAK_KAMPUS_JAM { get; set; }
        public Nullable<int> ID_ROAD_MAP_PENELITIAN { get; set; }
        public string OUTCOME { get; set; }
        public Nullable<decimal> DANA_PRIBADI { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string NPP1 { get; set; }
        public string NPP2 { get; set; }
        public Nullable<bool> IS_SETUJU_PRODI { get; set; }
        public Nullable<bool> IS_SETUJU_DEKAN { get; set; }
        public Nullable<int> BEBAN_SKS_ANGGOTA { get; set; }
        public Nullable<bool> IS_SETUJU_LPPM { get; set; }
        public string NPP_REVIEWER { get; set; }
        public Nullable<decimal> DANA_SETUJU { get; set; }
        public Nullable<double> PAJAK { get; set; }
        public Nullable<decimal> DANA_REKOMEN { get; set; }
        public byte[] LAPORAN { get; set; }
        public Nullable<bool> IS_SETUJU_PUSTAKAWAN { get; set; }
        public Nullable<bool> IS_SELESAI { get; set; }
        public byte[] LAPORAN1 { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string USER_ID { get; set; }
        public byte[] FILE_OUTCOME { get; set; }
    }
}
