//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_ROLE
    {
        public int ID_SISTEM_INFORMASI { get; set; }
        public Nullable<int> ID_ROLE { get; set; }
        public string NPP { get; set; }
        public Nullable<System.DateTime> TGL_AWAL_AKTIF { get; set; }
        public Nullable<System.DateTime> TGL_AKHIR_AKTIF { get; set; }
        public Nullable<int> ID_FAKULTAS { get; set; }
        public int ID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
