//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace silppm_v1e2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PUBLIKASI_SEMINAR
    {
        public int ID_OUTCOME_PROSIDING { get; set; }
        public Nullable<int> ID_PROPOSAL { get; set; }
        public string JUDUL { get; set; }
        public Nullable<int> ID_LEVEL_SEMINAR { get; set; }
        public string NAMA_JURNAL { get; set; }
        public string ISSN { get; set; }
        public string DOI { get; set; }
    
        public virtual REF_LEVEL_SEMINAR REF_LEVEL_SEMINAR { get; set; }
        public virtual TBL_PENELITIAN TBL_PENELITIAN { get; set; }
    }
}
